### ISSUE TITLE
initCobraToolbox messes up my git

### ISSUE THREAD

**Issue by akaviaLab** [opencobra/cobratoolbox#1030]
There seems to be something weird going on with initCobraToolbox.

It tests the solvers. Which means it calls changeCobraSolver.
When it gets to testing the dqqMinos solver, some weird bug happens.

The solver makes the temporary directory MPS, as well as the temporary files fort.4 and fort.10.
It gets to line 414 in solveCobraLP and tries to run the DQQ solver.
This seems to fail, and no file is created.
Line 415:solveCobraLP attempts to read the solution file. And fails.
This means that the error is caught by line 415:changeCobraSolver, and the solver is declared as not OK.

The problem is that the cleanup lines (lines 454-465 solveCobraLP) don't get executed.
This leaves MPS, fort.4 and fort.10 in binary directory.

At this point, git update fails, whether using terminal git, initCobraToolbox call to git or MATLAB.develTools. Which means I can't update the fork any more.

I can delete the wrong files and then update the fork.
The problem is that these files seem to be created every time I run initCobraToolbox, which is a problem.

I'm not sure how to fix this.

**I hereby confirm that I have:**

- [X] Tried to solve the issue on my own
- [X] Retried to run my code with the latest version of The COBRA Toolbox
- [X] Checked that a similar issue has not already been opened

**Comment by tpfau** [comment]
my fault. :/

I'll try to fix this as soon as possible.

**Comment by tpfau** [comment]
This should be fixed with the changes in #1032.
The reason is, that `changeCobraSolver` now actively tries the tested solver if it "should" be compatible with the OS in order to clearly indicate what is working and what is not working on the actual system. Earlier, this was only a "should be working" now it is a "it is working", i.e. if a normal `changeCobraSolver`  returns `true`, than the solver was tested and did not throw an error.

I tried my new modifications on a High Sierra 2017b installation, where this seems to work fine. Lets see what the CI says.

**Comment by akaviaLab** [comment]
Seems to work for me. Closing.
