### ISSUE TITLE
Cobra unable to run optimizeCbModel

### ISSUE THREAD

**Issue by manas-kohli** [opencobra/cobratoolbox#1937]
I can't seem to be able to run optimizeCbModel for even Recon3D:

osenseStr = 'max';
minNorm = 'zero';
allowLoops = 1;
zeroNormApprox = 'all';
FBAsolutionBounded_Recon = optimizeCbModel(Recon3D, osenseStr,minNorm, allowLoops, zeroNormApprox)

**Index in position 1 exceeds array bounds.

Error in optimizeCbModel (line 786)
        solution.y = solution.dual(1:nMets,1);**

**I hereby confirm that I have:**

- [X ] Tried to solve the issue on my own
- [X ] Retried to run my code with the latest version of The COBRA Toolbox
- [X ] Checked that a similar issue has not already been opened

*(Note: You may replace [ ] with [X] to check the box)*

**Comment by rmtfleming** [comment]
fixed in master version

On Wed, 16 Feb 2022 at 15:16, manas-kohli ***@***.***> wrote:
>
> I can't seem to be able to run optimizeCbModel for even Recon3D:
>
> osenseStr = 'max';
> minNorm = 'zero';
> allowLoops = 1;
> zeroNormApprox = 'all';
> FBAsolutionBounded_Recon = optimizeCbModel(Recon3D, osenseStr,minNorm, allowLoops, zeroNormApprox)
>
> **Index in position 1 exceeds array bounds.
>
> Error in optimizeCbModel (line 786)
> solution.y = solution.dual(1:nMets,1);**
>
> I hereby confirm that I have:
>
> [X ] Tried to solve the issue on my own
> [X ] Retried to run my code with the latest version of The COBRA Toolbox
> [X ] Checked that a similar issue has not already been opened
>
> (Note: You may replace [ ] with [X] to check the box)
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
--
Mr. Ronan MT Fleming B.V.M.S. Dip. Math. Ph.D.
----------------------------------------------------------------------------
Associate Professor,
School of Medicine,
National University of Ireland, Galway.
&
Assistant Professor,
Division of Systems Biomedicine and Pharmacology,
Leiden Academic Centre for Drug Research,
Faculty of Science,
Leiden University.
https://www.universiteitleiden.nl/en/staffmembers/ronan-fleming
&
H2020 Project Coordinator,
Systems Medicine of Mitochondrial Parkinson’s Disease,
http://sysmedpd.eu
----------------------------------------------------------------------------
Peer-reviewed publications: https://goo.gl/FZPG23
Mobile:  +353 852 109 806
Skype: ronan.fleming
----------------------------------------------------------------------------
(This message is confidential and may contain privileged information.
It is intended for the named recipient only. If you receive it in
error please notify me and permanently delete the original message and
any copies.)
