### ISSUE TITLE
testSolvers MILP fails because of incorrect merge

### ISSUE THREAD

**Issue by ssahebkashaf** [opencobra/cobratoolbox#49]
When attempting to test solvers, MILP test fails. Upon investigation, a syntax error is at fault due to an incorrect merge of git commit. See here:

https://github.com/opencobra/cobratoolbox/blob/5e705c0059de8dda6faefa8fb0eb2107d88b63f1/solvers/solveCobraMILP.m#L62

Removing the offending lines solves the problem and the test proceeds as intended.

**Comment by ssahebkashaf** [comment]
In the same file, the parameters variable is not initialized so when the nargin is equal to 1, the execution fails.

**Comment by longfeimao** [comment]
Hi there

Thanks for pointing out the issues; they are now fixed in a newer version of " solveCobraMILP" function as suggested.

Best wishes 
 
Longfei Mao, Ph.D.
-----------------------------------------------------------------------------------
Research Associate (Collaborateur Scientifique)
Systems Biochemistry Group,
Luxembourg Centre for Systems Biomedicine 

UNIVERSITY OF LUXEMBOURG
CAMPUS BELVAL
7, avenue des Hauts-Fourneaux
L-4362 Esch-Belval
T +352 46 66 44 5514
F +352 46 66 44 35514
-----------------------------------------------------------------------------------
 
http://wwwen.uni.lu/lcsb/research/systems_biochemistry
 
longfeimao99@gmail.com
longfei.mao@uni.lu
www.lcsb.lu
----------------------------

**Comment by laurentheirendt** [comment]
Closing as fixed.
