### ISSUE TITLE
resultCell = FEA(model, rxnSet, group)

### ISSUE THREAD

**Issue by rmtfleming** [opencobra/cobratoolbox#623]
@marouenbg pls update the header, usage example, reference to the paper introducing the method, area all arguments annotated correctly? is model used?

**Comment by marouenbg** [comment]
Hi @rmtfleming, I updated FEA header in [628](https://github.com/opencobra/cobratoolbox/pull/628)

model is used, it is highlighted because it is called in eval().
There isn't a particular paper that described the method, it is just a simple set enrichment analysis with multiple test correction as in gene set enrichment analysis.

**Comment by laurentheirendt** [comment]
Issue resolved in PR #628. Thanks.
