### ISSUE TITLE
tutorial_uniformSampling.m bugs

### ISSUE THREAD

**Issue by wbryant** [opencobra/cobratoolbox#760]
I am having great difficulty getting this tutorial to run for me.  I am using MATLAB 2015b on Mac OSX El Capitan.  I cloned the master repo to install it fresh on my system.  Since fastFVA requires CPLEX I also installed and linked the latest CPLEX 12.71.  I wonder if all of these bugs are related to my version of MATLAB, but hacking fastFVA can only get me so far: I have no idea where the function 'cplexFVA1271' is defined.

Bugs so far:

* line 105: bm in this model is 'Biomass_Ecoli_core_N(w/GAM)-Nmet2’ (model found at 'test/testGrowthExpMatch/ecoli_core_model.mat’)
* line 131: Error: 'There is no capsize property on the ErrorBar class.’ - plots without this property (introduced after 2015b?).
* lines 137-139: yyaxis was introduced in 2016a, so these lines did not work for me (2015b); there doesn’t seem to be a straightforward workaround - perhaps 'try … catch' to skip if it doesn’t work?  I worked on a workaround, but it would be messy having two alternatives in the tutorial depending on MATLAB version, not sure what should be done.
* chrrSampler: requires CPLEX?  Perhaps should be mentioned at beginning of tutorial
* fastFVA (line 643): 'Undefined function or variable 'binVersion’.'
* fastFVA (line 442): 'Undefined function 'cplexFVA1271' for input arguments of type 'struct’.'

**I hereby confirm that I have:**

- [x] Tried to solve the issue on my own
- [x] Retried to run my code with the latest version of The COBRA Toolbox
- [x] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

EDIT: expanded on yyaxis workaround

**Comment by syarra** [comment]
Hi @wbryant,

Thanks for reporting these issues.
Did you run `initCobraToolbox` before trying to run the tutorial?
`initCobraToolbox` adjusts your paths and update all submodules (where the `cplexFVA1271` function is).

The version of the uniformSampling tutorial that you are trying to run has been updated yesterday and does not rely anymore on the ecoli_core model. Please update your COBRAToolbox to get the latest version of the tutorial.

If you still have issues with FastFVA this might be due to your version of MATLAB and/or your macOS version. You may find instructions to generate new mex file [here](https://github.com/opencobra/cobratoolbox/tree/master/external/fastFVAmex).

If you have any question or issue, please ping me!

**Comment by wbryant** [comment]
Thanks @syarra I'll try the steps you suggestt and let you know how it goes!

**Comment by wbryant** [comment]
Despite banging my head against this for a day I can't get MATLAB mex to play nice with Xcode, which is to say I have been unable to produce the mex file.  Does COBRA Toolbox create `cplexFVA1271`?  I still cannot find it when I search the Toolbox after running `initCobraToolbox`.

Anyway, this could be a system-specific bug, so it would be a waste of time for me to continue fiddling when I could be evaluating another tutorial.  I will remove my name from the spreadsheet and hopefully someone else with a working CPLEX can follow it!

**Comment by rmtfleming** [comment]
@Gpreciat 
please edit the sampling code to call fluxVariability.m using the default matlab+solver implementation, then only if fastFVA is selected as the implementation option, and only when the installation is verified to be working, then fastFVA is run (try catch), otherwise it should switch back to the default implementation.
