### ISSUE TITLE
addReaction

### ISSUE THREAD

**Issue by deisygysi** [opencobra/cobratoolbox#989]
Parsing should fail gracefully, rather than crash at the parser when an inappropriate parameter name is passed in. @tpfau 

for i=1:length(Rule)
    model = addReaction(model, VHM_ID_r{i}, ...
        'reactionName', Descrip_reac{i},...
        'reactionFormula', React{i},...
        'geneRule', Rule{i},...
        'subSystem','Arginine biosynthesis');
end

for i=1:length(Rule)
    model = addReaction(model, VHM_ID_r{i}, ...
        'BAD_Name', Descrip_reac{i},...
        'reactionFormula', React{i},...
        'geneRule', Rule{i},...
        'subSystem','Arginine biosynthesis');
end

**I hereby confirm that I have:**

- [] Tried to solve the issue on my own
- [] Retried to run my code with the latest version of The COBRA Toolbox
- [] Checked that a similar issue has not already been opened

*(Note: You may replace [] with [X] to check the box)*

**Comment by tpfau** [comment]
Well..
This is due to backward compatability. As long as the old style is allowed, we need to convert variable parameters of an old style call to parameter/value pairs. Thus, if the first parameter provided is invalid, a (admittedly) bad error message is thrown. I'll try to catch this and give a more appropriate error message.

**Comment by tpfau** [comment]
This should be solved.
@deisygysi could you check, whether this now works for you on the latest development version?

**Comment by tpfau** [comment]
Seems to be solved. If its not, lease reopen the issue.

**Comment by laurentheirendt** [comment]
Thanks @deisygysi and @tpfau 👍
